# Generated by Django 3.0.4 on 2020-08-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='items',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='key',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='todo',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
