# Generated by Django 3.0.4 on 2020-08-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200814_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
