# Generated by Django 3.0.4 on 2020-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200817_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
