# Generated by Django 3.0.4 on 2020-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200817_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='iscompleted',
            new_name='isedited',
        ),
    ]
